### ISSUE TITLE
Didn't add "getblock" rpc command to bitcoin proxy

### ISSUE THREAD

**Issue by BitcoinMechanic** [chrisguida/bwt-wrapper#1]
![Screen Shot 2021-11-24 at 5 59 09 PM](https://user-images.githubusercontent.com/45926711/143365382-655419dc-580a-4dea-b781-30c886fc71cc.png)

**Comment by chrisguida** [comment]
Fixed by [4b6e97c8dd47dade1d8d2343703aa68c35d342ec](https://github.com/Start9Labs/bwt-wrapper/commit/4b6e97c8dd47dade1d8d2343703aa68c35d342ec), still needs testing

**Comment by BitcoinMechanic** [comment]
Will test

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by BitcoinMechanic** [comment]
Fixed
