### ISSUE TITLE
Randomly crashes with the following error

### ISSUE THREAD

**Issue by BitcoinMechanic** [chrisguida/bwt-wrapper#2]
![Screen Shot 2021-11-24 at 6 01 40 PM](https://user-images.githubusercontent.com/45926711/143365449-f14a5c3f-1ba8-4a18-b1d2-42352a8111ce.png)

**Comment by BitcoinMechanic** [comment]
Embassy still says that it's running after it crashes.

**Comment by chrisguida** [comment]
Copied this issue to the new repo. This repo is deprecated.

**Comment by chrisguida** [comment]
> Embassy still says that it's running after it crashes.

This is because it's in a restart loop
